language: go

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.0

go:
  - 1.24.x

script:
  - go vet ./...
  - golangci-lint run
  - go test -short -timeout 1h ./...
  - go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb
